name: tests

on:
  push:
  pull_request:

jobs:
  host-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: ESPressio-Observable
      - uses: actions/checkout@v4
        with:
          repository: ESPressio-Development-Platform/ESPressio-System
          ref: main
          path: ESPressio-System
      - name: Configure
        run: cmake -S ESPressio-Observable/tests -B build -DESPRESSIO_SYSTEM_DIR=${{ github.workspace }}/ESPressio-System/src
      - name: Build
        run: cmake --build build --parallel
      - name: Test
        run: ctest --test-dir build --output-on-failure
